### PR TITLE
Imaging 159 1

### PR DESCRIPTION
**Pull request by gwlucastrig**

### CODE REVIEW

**Comment by gwlucastrig** [comment]
Found a mistake in the example class ExampleReadFloatingPointData.java.  It incorrectly used JpegImagingParameters instead of TiffImagingParameters.

**Review by kinow — COMMENTED** [review]
@gwlucastrig having a look at the PR's for this repo. This one has conflicts that are hard to fix (117 files changed). Do you remember what was changed here? Are you able to rebase and fix conflicts? Thanks!

**Comment by gwlucastrig** [comment]
Not sure what's going on.  I believe I changed just the one file.  I guess we can discard this PR.

Probably my usual incompetence with all things git.

**Comment by kinow** [comment]
Strange, maybe I changed lots of files in my branch, then the conflicts appeared here? If you remember which file you changed you should be able to re-create it, or you can try to rebase and fix conflicts https://docs.github.com/en/get-started/using-git/resolving-merge-conflicts-after-a-git-rebase

**Comment by gwlucastrig** [comment]
Withdrawn due to issues related to the incorrect use of git/github.

**Pull request closed without merging**
